name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install  # Adjust this based on your package manager

      - name: Build the project
        run: npm run build  # Adjust based on your project's build process

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}  # Vercel token stored in GitHub Secrets
          vercel-args: "--prod"  # To deploy to production
          working-directory: ./  # Change if the project is located in a subdirectory
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Optional, for GitHub integration
